CREATE TABLE customers (
    id INT PRIMARY KEY AUTO_INCREMENT,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(200) UNIQUE NOT NULL,
    phone VARCHAR(20),
    age INT CHECK (age >= 18),
    city VARCHAR(100),
    state VARCHAR(50),
    country VARCHAR(50) DEFAULT 'USA',
    zipcode VARCHAR(10),
    address TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    status ENUM('active', 'inactive', 'pending') DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    notes TEXT,
    website VARCHAR(255),
    company VARCHAR(100),
    job_title VARCHAR(100),
    salary DECIMAL(10,2),
    birth_date DATE,
    last_login DATETIME,
    profile_picture VARCHAR(255),
    preferences JSON
); 